name: Agregadora Retornados

on:
  workflow_dispatch:
  #schedule:
  #  - cron:  '0 4 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Convert google sheet to csv
      run: |-
        wget -O retornados/agregadora.csv --no-check-certificate "https://docs.google.com/spreadsheets/d/e/2PACX-1vQ3tq2u681wWoST-f3QJw9B8sMoHl6gGpFfW2_Hjbo7eodxD7nhVZvSmzvGs-4kGw/pub?output=csv"
    - name: CSV to JSON
      run: ./dasel -r csv -w json < retornados/agregadora.csv > retornados/agregadora.json
    - name: Minify JSON
      run: |-
        jq -r tostring retornados/agregadora.json > retornados/agregadora.min.json
    - name: Commit and push changes
      run: |-
        git diff
        git config user.name "Automated"
        git config user.email "---"
        git diff --quiet || (git add -A && git commit -m "Updated Agregadora Retornados")
        git push
