name: Fetch articles
on:
  workflow_dispatch:
  schedule:
    - cron:  '*/50 10 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Download Feed
      run: |-
        curl "https://www.publico.pt/api/search/?size=20&type=noticia" | jq -r tostring > hardnews.json
    - name: Download Feed
      run: |-
        curl "https://www.publico.pt/api/search/?size=6&type=opiniao" | jq -r tostring > opinion.json
    - name: Commit and push changes
      run: |-
        git diff
        git config user.name "Automated"
        git config user.email "---"
        git diff --quiet || (git add -A && git commit -m "Updated with latest articles")
        git push
