name: Fetch articles
on:
  workflow_dispatch:
    schedule:
    - cron:  '*/60 8-22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Download Feed
      run: |-
        curl "https://www.publico.pt/api/content/home?&op=false&size=22" | jq -r tostring > hardnews.json
    - name: Download Feed
      run: |-
        curl "https://www.publico.pt/api/page/hp/opinion" | jq -r tostring > opinion.json
    - name: Commit and push changes
      run: |-
        git diff
        git config user.name "Automated"
        git config user.email "---"
        git pull
        git diff --quiet || (git add -A && git commit -m "Updated with latest articles")
        git push
