name: Fetch fires
on:
  workflow_dispatch:
  schedule:
    - cron:  '*/20 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Download Feed
      run: |-
        curl "https://api-dev.fogos.pt/new/fires" | jq -r tostring > fires.json
    - name: Commit and push changes
      run: |-
        git diff
        git config user.name "Automated"
        git config user.email "---"
        git pull
        git diff --quiet || (git add -A && git commit -m "Update fires")
        git push
