name: Headlines PT
on:
  workflow_dispatch:
  schedule:
    - cron:  '*/15 6-23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build
      run: npx puppeteer browsers install chrome
    - name: Scrape ECO
      run: node ecoHeadline.js
    - name: Scrape Público
      run: node publicoHeadline.js
    - name: Scrape Observador
      run: node obsHeadline.js
    - name: Scrape CNN Portugal
      run: node cnnHeadline.js
    - name: Scrape Correio da Manhã
      run: node cmHeadline.js
    - name: Scrape Economico
      run: node economicoHeadline.js
    - name: Scrape RTP Notícias
      run: node rtpHeadline.js
    - name: Scrape Novo
      run: node novoHeadline.js
    - name: Scrape Renascença
      run: node renascencaHeadline.js
    - name: Scrape Jornal i
      run: node jornaliHeadline.js
    - name: Scrape Notícias ao Minuto
      run: node noticiasaominutoHeadline.js
    - name: Scrape Expresso
      run: node expressoHeadline.js
    - name: Scrape SIC Notícias
      run: node sicHeadline.js
    - name: Scrape DN
      run: node dnHeadline.js
    - name: Scrape JN
      run: node jnHeadline.js
    - name: Scrape Dinheiro Vivo
      run: node dinheirovivoHeadline.js
    - name: Scrape TSF
      run: node tsfHeadline.js
    - name: Scrape Negócios
      run: node negociosHeadline.js
    - name: Edit headline--eco.json
      run: |-
        jq '{title: ."0", url: ."1", fetchDate: ."2", media: "Eco"}' headline--eco.json >headlines/headline--eco.json
    - name: Edit headline--publico.json
      run: |-
        jq '{title: ."0", url: ."1", fetchDate: ."2", media: "Público"}' headline--publico.json >headlines/headline--publico.json
    - name: Edit headline--observador.json
      run: |-
        jq '{title: ."0", url: ."1", media: "Observador", fetchDate: (now | todateiso8601)}' headline--observador.json >headlines/headline--observador.json
    - name: Edit headline--cnn.json
      run: |-
        jq '{title: ."0", url: ."1", fetchDate: ."2", media: "CNN Portugal"}' headline--cnn.json >headlines/headline--cnn.json
    - name: Edit headline--cm.json
      run: |-
        jq '{title: ."0", url: ."1", media: "Correio da Manhã", fetchDate: (now | todateiso8601)}' headline--cm.json >headlines/headline--cm.json
    - name: Edit headline--economico.json
      run: |-
        jq '{title: ."0", url: ."1", fetchDate: ."2", media: "Económico"}' headline--economico.json >headlines/headline--economico.json
    - name: Edit headline--rtp.json
      run: |-
        jq '{title: ."0", url: ."1", fetchDate: ."2", media: "RTP Notícias"}' headline--rtp.json >headlines/headline--rtp.json
    - name: Edit headline--novo.json
      run: |-
        jq '{title: ."0", url: ."1", media: "Novo", fetchDate: (now | todateiso8601)}' headline--novo.json >headlines/headline--novo.json
    - name: Edit headline--renascenca.json
      run: |-
        jq '{title: ."0", url: ."1", fetchDate: ."2", media: "Renascença"}' headline--renascenca.json >headlines/headline--renascenca.json
    - name: Edit headline--jornali.json
      run: |-
        jq '{title: ."0", url: ."1", media: "Jornal i", fetchDate: (now | todateiso8601)}' headline--jornali.json >headlines/headline--jornali.json
    - name: Edit headline--noticiasaominuto.json
      run: |-
        jq '{title: ."0", url: ."1", media: "Notícias ao Minuto", fetchDate: (now | todateiso8601)}' headline--noticiasaominuto.json >headlines/headline--noticiasaominuto.json
    - name: Edit headline--expresso.json
      run: |-
        jq '{title: ."0", url: ."1", media: "Expresso", fetchDate: (now | todateiso8601)}' headline--expresso.json >headlines/headline--expresso.json
    - name: Edit headline--sicnoticias.json
      run: |-
        jq '{title: ."0", url: ."1", fetchDate: ."2", media: "SIC Notícias"}' headline--sicnoticias.json >headlines/headline--sicnoticias.json
    - name: Edit headline--dn.json
      run: |-
        jq '{title: ."0", url: ."1", media: "Diário de Notícias", fetchDate: (now | todateiso8601)}' headline--dn.json >headlines/headline--dn.json
    - name: Edit headline--jn.json
      run: |-
        jq '{title: ."0", url: ."1", media: "Jornal de Notícias", fetchDate: (now | todateiso8601)}' headline--jn.json >headlines/headline--jn.json
    - name: Edit headline--dinheirovivo.json
      run: |-
        jq '{title: ."0", url: ."1", fetchDate: ."2", media: "Dinheiro Vivo"}' headline--dinheirovivo.json >headlines/headline--dinheirovivo.json
    - name: Edit headline--tsf.json
      run: |-
        jq '{title: ."0", url: ."1", fetchDate: ."2", media: "TSF"}' headline--tsf.json >headlines/headline--tsf.json
    - name: Edit headline--negocios.json
      run: |-
        jq '{title: ."0", url: ."1", media: "Negócios", fetchDate: (now | todateiso8601)}' headline--negocios.json >headlines/headline--negocios.json
    - name: Merge files
      run: |-
        jq -s . headlines/headline--cnn.json headlines/headline--cm.json headlines/headline--dinheirovivo.json headlines/headline--dn.json headlines/headline--eco.json headlines/headline--economico.json headlines/headline--expresso.json headlines/headline--jn.json headlines/headline--jornali.json headlines/headline--negocios.json headlines/headline--noticiasaominuto.json headlines/headline--novo.json headlines/headline--observador.json headlines/headline--publico.json headlines/headline--renascenca.json headlines/headline--rtp.json headlines/headline--sicnoticias.json headlines/headline--tsf.json | jq -r tostring > headlines/headlinespt.json
    - name: Commit and push changes
      run: |-
        git diff
        git config user.name "Automated"
        git config user.email "---"
        git pull
        git diff --quiet || (git add -A && git commit -m "Updated Headlines PT")
        git push
