name: hello
on:
  repository_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Commit and push changes
      run: |-
        git diff
        git config user.name "Automated"
        git config user.email "---"
        git diff --quiet || (git add -A && git commit -m "hello")
        git push
