name: Fetch latest gastronomia
on: 
   workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Download Feed
      run: |-
        curl "https://www.publico.pt/api/search/?size=10&tags=gastronomia" | jq -r tostring > latest--gastronomia.json
    - name: Download Feed
      run: |-
        git diff
        git config user.name "Automated"
        git config user.email "---"
        git diff --quiet || (git add -A && git commit -m "Updated with latest gastronomia articles")
        git push
