name: Mortes 2025

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 4 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Convert google sheet to csv
      run: |-
        wget -O deaths-2025.csv --no-check-certificate "https://docs.google.com/spreadsheets/d/e/2PACX-1vSVuB2SVkCikMyRMY1QSIdB-lNQ8BfgyU_uWJisv0jZPbuo1730h1YnDB03RWbmdBy9OsLxIAimhqnI/pub?output=csv"
    - name: Commit and push changes
      run: |-
        git diff
        git config user.name "Automated"
        git config user.email "---"
        git pull
        git diff --quiet || (git add -A && git commit -m "Updated Mortes 2025")
        git push
