name: Fetch politica news
on: 
  workflow_dispatch:
  schedule:
    - cron:  '0 8-20 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
    - name: Download Feed
      run: |-
        curl "https://www.publico.pt/api/search/?size=20&tags=politica" | jq -r tostring > politica.json
    - name: Commit and push changes
      run: |-
        git diff
        git config user.name "Automated"
        git config user.email "---"
        git pull
        git diff --quiet || (git add -A && git commit -m "Updated politica news")
        git push
