name: Scraper CNN

on:
  workflow_dispatch:
  #schedule:
  #  - cron:  '0 4 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build
      run: npm install rss-to-json --save
    - name: Scrape
      run: node rss-to-json--cnn.js
    - name: Edit cnnportugal.json
      run: |-
        jq -r '.items[:10] | map(.date_published = (.date_published | strftime("%s" | strptime("%s") | strftime("%Y-%m-%dT%H:%M:%SZ")) | .url = .link | del(.published, .link)) | map({title, url, date_published, media: "CNN Portugal"})' cnnportugal.json 
    - name: Commit and push changes
      run: |-
        git diff
        git config user.name "Automated"
        git config user.email "---"
        git diff --quiet || (git add -A && git commit -m "Updated rss-to-json--cnn.js")
        git push
