name: Scraper CNN

on:
  workflow_dispatch:
  #schedule:
  #  - cron:  '0 4 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build
      run: npm install rss-to-json --save
    - name: Scrape
      run: node rss-to-json--cnn.js
    - name: Edit cnnportugal.json
      run: |-
        jq '.items[:10] | map(.date_published = .published | .url = .link | del(.published, .link)) | map({title, url, date_published: (.date_published / 1000 | strftime("%Y-%m-%dT%H:%M.00Z")), media: "CNN Portugal"})' | jq -r tostring cnnportugal.json > digest/latest--cnnportugal2.json
    - name: Commit and push changes
      run: |-
        git diff
        git config user.name "Automated"
        git config user.email "---"
        git diff --quiet || (git add -A && git commit -m "Updated rss-to-json--cnn.js")
        git push
